# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "industries", :force => true do |t|
    t.column "name",      :string,  :limit => 50, :default => "", :null => false
    t.column "sector_id", :integer,                               :null => false
    t.column "url",       :string,  :limit => 50, :default => "", :null => false
    t.column "status",    :string,  :limit => 15
  end

  create_table "investor_performances", :force => true do |t|
    t.column "investor_id",       :integer,                                :default => 0, :null => false
    t.column "date",              :date,                                                  :null => false
    t.column "pm_id",             :integer
    t.column "actualized_return", :decimal, :precision => 10, :scale => 4
    t.column "after_cost_return", :decimal, :precision => 10, :scale => 4
  end

  add_index "investor_performances", ["investor_id", "date", "pm_id"], :name => "ip_unique", :unique => true
  add_index "investor_performances", ["date"], :name => "ip_date"

  create_table "investors", :force => true do |t|
    t.column "memory", :integer,                               :null => false
    t.column "status", :string,  :limit => 15, :default => "", :null => false
  end

  add_index "investors", ["memory"], :name => "investor_unique", :unique => true

  create_table "pm_performances", :force => true do |t|
    t.column "pm_id",             :integer,                                :default => 0,   :null => false
    t.column "optimized_date",    :date,                                                    :null => false
    t.column "actualized_return", :decimal, :precision => 10, :scale => 4, :default => 0.0
    t.column "actualized_date",   :date
    t.column "after_cost_return", :float
  end

  add_index "pm_performances", ["pm_id", "actualized_date"], :name => "pmp_unique", :unique => true
  add_index "pm_performances", ["actualized_date"], :name => "pmp_adate"

  create_table "pms", :force => true do |t|
    t.column "memory",     :integer,                               :null => false
    t.column "confidence", :integer,                               :null => false
    t.column "status",     :string,  :limit => 15, :default => "", :null => false
  end

  add_index "pms", ["memory", "confidence"], :name => "pm_unique", :unique => true

  create_table "portfolio_items", :force => true do |t|
    t.column "pm_id",        :integer,                                              :default => 0,  :null => false
    t.column "date",         :date,                                                                 :null => false
    t.column "ticker",       :string,  :limit => 10,                                :default => "", :null => false
    t.column "fraction",     :decimal,               :precision => 10, :scale => 4,                 :null => false
    t.column "shares",       :integer
    t.column "book_value",   :float
    t.column "market_value", :float
  end

  add_index "portfolio_items", ["pm_id", "date", "ticker"], :name => "pi_unique", :unique => true
  add_index "portfolio_items", ["date", "pm_id"], :name => "pi_date"

  create_table "portfolios", :force => true do |t|
    t.column "user_id",       :integer,               :null => false
    t.column "profile_id",    :integer,               :null => false
    t.column "change",        :float
    t.column "start_date",    :date
    t.column "shares",        :integer, :limit => 10
    t.column "buy_price",     :float
    t.column "current_price", :float
  end

  create_table "profiles", :force => true do |t|
    t.column "ticker",      :string,  :limit => 10, :default => "",    :null => false
    t.column "name",        :string,  :limit => 60, :default => "",    :null => false
    t.column "currency",    :string,  :limit => 10, :default => "USD", :null => false
    t.column "status",      :string,  :limit => 15
    t.column "industry_id", :integer,                                  :null => false
    t.column "quote_type",  :string,  :limit => 10
    t.column "url",         :string,  :limit => 50
  end

  add_index "profiles", ["ticker"], :name => "profile_unique", :unique => true

  create_table "quotes", :force => true do |t|
    t.column "date",           :date,                                                                  :null => false
    t.column "open",           :decimal,               :precision => 10, :scale => 2,                  :null => false
    t.column "high",           :decimal,               :precision => 10, :scale => 2,                  :null => false
    t.column "low",            :decimal,               :precision => 10, :scale => 2,                  :null => false
    t.column "close",          :decimal,               :precision => 10, :scale => 2,                  :null => false
    t.column "volume",         :integer,                                                               :null => false
    t.column "adjusted_close", :decimal,               :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "rate_of_return", :decimal,               :precision => 12, :scale => 6
    t.column "ticker",         :string,  :limit => 10,                                :default => "",  :null => false
    t.column "profile_id",     :integer,                                              :default => 0,   :null => false
  end

  add_index "quotes", ["ticker", "date"], :name => "quote_unique", :unique => true

  create_table "risk_free_rates", :force => true do |t|
    t.column "date",        :date,                                   :null => false
    t.column "t_bill_rate", :decimal, :precision => 10, :scale => 4
  end

  create_table "sectors", :force => true do |t|
    t.column "name",   :string, :limit => 40, :default => "", :null => false
    t.column "url",    :string, :limit => 50, :default => "", :null => false
    t.column "status", :string, :limit => 15, :default => "", :null => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "users", :force => true do |t|
    t.column "name",            :string, :limit => 100, :default => "", :null => false
    t.column "hashed_password", :string, :limit => 40
  end

end
